create table TOPICS (
  TOPICID INTEGER not null,
  GAME CHAR(2) not null,
  PAGES INTEGER,
  LAST_PROCESSED_PAGE INTEGER,
  DATE_UPDATED TIMESTAMP,
  primary key (TOPICID)
);

create table CLANS (
  CODE CHAR(5) not null,
  GAME CHAR(2) not null,
  NAME VARCHAR(100),
  DATE_REQUESTED TIMESTAMP,
  DATE_UPDATED TIMESTAMP,
  STATUS INTEGER,
  primary key (code)
);
